// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// DeviceConfigurationKeyIdType type
type DeviceConfigurationKeyIdType uint

// DeviceConfigurationKeyValueStringType type
type DeviceConfigurationKeyValueStringType string

// DeviceConfigurationKeyNameType type
type DeviceConfigurationKeyNameType DeviceConfigurationKeyNameEnumType

// DeviceConfigurationKeyNameEnumType type
type DeviceConfigurationKeyNameEnumType string

// DeviceConfigurationKeyNameEnumType constants
const (
	DeviceConfigurationKeyNameEnumTypePeakPowerOfPVSystem         DeviceConfigurationKeyNameEnumType = "peakPowerOfPvSystem"
	DeviceConfigurationKeyNameEnumTypePvCurtailmentLimitFactor    DeviceConfigurationKeyNameEnumType = "pvCurtailmentLimitFactor"
	DeviceConfigurationKeyNameEnumTypeAsymmetricChargingSupported DeviceConfigurationKeyNameEnumType = "asymmetricChargingSupported"
	DeviceConfigurationKeyNameEnumTypeCommunicationsStandard      DeviceConfigurationKeyNameEnumType = "communicationsStandard"
)

// DeviceConfigurationKeyValueTypeType type
type DeviceConfigurationKeyValueTypeType string

// DeviceConfigurationKeyValueTypeType constants
const (
	DeviceConfigurationKeyValueTypeTypeBoolean      DeviceConfigurationKeyValueTypeType = "boolean"
	DeviceConfigurationKeyValueTypeTypeDate         DeviceConfigurationKeyValueTypeType = "date"
	DeviceConfigurationKeyValueTypeTypeDatetime     DeviceConfigurationKeyValueTypeType = "dateTime"
	DeviceConfigurationKeyValueTypeTypeDuration     DeviceConfigurationKeyValueTypeType = "duration"
	DeviceConfigurationKeyValueTypeTypeString       DeviceConfigurationKeyValueTypeType = "string"
	DeviceConfigurationKeyValueTypeTypeTime         DeviceConfigurationKeyValueTypeType = "time"
	DeviceConfigurationKeyValueTypeTypeScalednumber DeviceConfigurationKeyValueTypeType = "scaledNumber"
)

// DeviceConfigurationKeyValueValueType complex type
type DeviceConfigurationKeyValueValueType struct {
	Boolean      *bool                                  `json:"boolean,omitempty"`
	Date         *string                                `json:"date,omitempty"`
	DateTime     *string                                `json:"dateTime,omitempty"`
	Duration     *string                                `json:"duration,omitempty"`
	String       *DeviceConfigurationKeyValueStringType `json:"string,omitempty"`
	Time         *string                                `json:"time,omitempty"`
	ScaledNumber *ScaledNumberType                      `json:"scaledNumber,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueValueType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueValueType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueValueElementsType complex type
type DeviceConfigurationKeyValueValueElementsType struct {
	Boolean      *ElementTagType           `json:"boolean,omitempty"`
	Date         *ElementTagType           `json:"date,omitempty"`
	DateTime     *ElementTagType           `json:"dateTime,omitempty"`
	Duration     *ElementTagType           `json:"duration,omitempty"`
	String       *ElementTagType           `json:"string,omitempty"`
	Time         *ElementTagType           `json:"time,omitempty"`
	ScaledNumber *ScaledNumberElementsType `json:"scaledNumber,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueValueElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueValueElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDataType complex type
type DeviceConfigurationKeyValueDataType struct {
	KeyId             *DeviceConfigurationKeyIdType         `json:"keyId,omitempty"`
	Value             *DeviceConfigurationKeyValueValueType `json:"value,omitempty"`
	IsValueChangeable *bool                                 `json:"isValueChangeable,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDataElementsType complex type
type DeviceConfigurationKeyValueDataElementsType struct {
	KeyId             *ElementTagType                               `json:"keyId,omitempty"`
	Value             *DeviceConfigurationKeyValueValueElementsType `json:"value,omitempty"`
	IsValueChangeable *ElementTagType                               `json:"isValueChangeable,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueListDataType complex type
type DeviceConfigurationKeyValueListDataType struct {
	DeviceConfigurationKeyValueData []DeviceConfigurationKeyValueDataType `json:"deviceConfigurationKeyValueData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueListDataSelectorsType complex type
type DeviceConfigurationKeyValueListDataSelectorsType struct {
	KeyId *DeviceConfigurationKeyIdType `json:"keyId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDescriptionDataType complex type
type DeviceConfigurationKeyValueDescriptionDataType struct {
	KeyId       *DeviceConfigurationKeyIdType        `json:"keyId,omitempty"`
	KeyName     *string                              `json:"keyName,omitempty"`
	ValueType   *DeviceConfigurationKeyValueTypeType `json:"valueType,omitempty"`
	Unit        *string                              `json:"unit,omitempty"`
	Label       *LabelType                           `json:"label,omitempty"`
	Description *DescriptionType                     `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDescriptionDataElementsType complex type
type DeviceConfigurationKeyValueDescriptionDataElementsType struct {
	KeyId       *ElementTagType `json:"keyId,omitempty"`
	KeyName     *ElementTagType `json:"keyName,omitempty"`
	ValueType   *ElementTagType `json:"valueType,omitempty"`
	Unit        *ElementTagType `json:"unit,omitempty"`
	Label       *ElementTagType `json:"label,omitempty"`
	Description *ElementTagType `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDescriptionDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDescriptionDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDescriptionListDataType complex type
type DeviceConfigurationKeyValueDescriptionListDataType struct {
	DeviceConfigurationKeyValueDescriptionData []DeviceConfigurationKeyValueDescriptionDataType `json:"deviceConfigurationKeyValueDescriptionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDescriptionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDescriptionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueDescriptionListDataSelectorsType complex type
type DeviceConfigurationKeyValueDescriptionListDataSelectorsType struct {
	KeyId   *DeviceConfigurationKeyIdType `json:"keyId,omitempty"`
	KeyName *string                       `json:"keyName,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueDescriptionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueDescriptionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueConstraintsDataType complex type
type DeviceConfigurationKeyValueConstraintsDataType struct {
	KeyId         *DeviceConfigurationKeyIdType         `json:"keyId,omitempty"`
	ValueRangeMin *DeviceConfigurationKeyValueValueType `json:"valueRangeMin,omitempty"`
	ValueRangeMax *DeviceConfigurationKeyValueValueType `json:"valueRangeMax,omitempty"`
	ValueStepSize *DeviceConfigurationKeyValueValueType `json:"valueStepSize,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueConstraintsDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueConstraintsDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueConstraintsDataElementsType complex type
type DeviceConfigurationKeyValueConstraintsDataElementsType struct {
	KeyId         *ElementTagType                               `json:"keyId,omitempty"`
	ValueRangeMin *DeviceConfigurationKeyValueValueElementsType `json:"valueRangeMin,omitempty"`
	ValueRangeMax *DeviceConfigurationKeyValueValueElementsType `json:"valueRangeMax,omitempty"`
	ValueStepSize *DeviceConfigurationKeyValueValueElementsType `json:"valueStepSize,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueConstraintsDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueConstraintsDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueConstraintsListDataType complex type
type DeviceConfigurationKeyValueConstraintsListDataType struct {
	DeviceConfigurationKeyValueConstraintsData []DeviceConfigurationKeyValueConstraintsDataType `json:"deviceConfigurationKeyValueConstraintsData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueConstraintsListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueConstraintsListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// DeviceConfigurationKeyValueConstraintsListDataSelectorsType complex type
type DeviceConfigurationKeyValueConstraintsListDataSelectorsType struct {
	KeyId *DeviceConfigurationKeyIdType `json:"keyId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m DeviceConfigurationKeyValueConstraintsListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *DeviceConfigurationKeyValueConstraintsListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
