// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// ElectricalConnectionIdType type
type ElectricalConnectionIdType uint

// ElectricalConnectionParameterIdType type
type ElectricalConnectionParameterIdType uint

// ElectricalConnectionMeasurandVariantType type
type ElectricalConnectionMeasurandVariantType ElectricalConnectionMeasurandVariantEnumType

// ElectricalConnectionMeasurandVariantEnumType type
type ElectricalConnectionMeasurandVariantEnumType string

// ElectricalConnectionMeasurandVariantEnumType constants
const (
	ElectricalConnectionMeasurandVariantEnumTypeAmplitude     ElectricalConnectionMeasurandVariantEnumType = "amplitude"
	ElectricalConnectionMeasurandVariantEnumTypeRms           ElectricalConnectionMeasurandVariantEnumType = "rms"
	ElectricalConnectionMeasurandVariantEnumTypeInstantaneous ElectricalConnectionMeasurandVariantEnumType = "instantaneous"
	ElectricalConnectionMeasurandVariantEnumTypeAngle         ElectricalConnectionMeasurandVariantEnumType = "angle"
	ElectricalConnectionMeasurandVariantEnumTypeCosphi        ElectricalConnectionMeasurandVariantEnumType = "cosPhi"
)

// ElectricalConnectionVoltageTypeType type
type ElectricalConnectionVoltageTypeType ElectricalConnectionVoltageTypeEnumType

// ElectricalConnectionVoltageTypeEnumType type
type ElectricalConnectionVoltageTypeEnumType string

// ElectricalConnectionVoltageTypeEnumType constants
const (
	ElectricalConnectionVoltageTypeEnumTypeAc ElectricalConnectionVoltageTypeEnumType = "ac"
	ElectricalConnectionVoltageTypeEnumTypeDc ElectricalConnectionVoltageTypeEnumType = "dc"
)

// ElectricalConnectionAcMeasurementTypeType type
type ElectricalConnectionAcMeasurementTypeType ElectricalConnectionAcMeasurementTypeEnumType

// ElectricalConnectionAcMeasurementTypeEnumType type
type ElectricalConnectionAcMeasurementTypeEnumType string

// ElectricalConnectionAcMeasurementTypeEnumType constants
const (
	ElectricalConnectionAcMeasurementTypeEnumTypeReal     ElectricalConnectionAcMeasurementTypeEnumType = "real"
	ElectricalConnectionAcMeasurementTypeEnumTypeReactive ElectricalConnectionAcMeasurementTypeEnumType = "reactive"
	ElectricalConnectionAcMeasurementTypeEnumTypeApparent ElectricalConnectionAcMeasurementTypeEnumType = "apparent"
	ElectricalConnectionAcMeasurementTypeEnumTypePhase    ElectricalConnectionAcMeasurementTypeEnumType = "phase"
)

// ElectricalConnectionPhaseNameType type
type ElectricalConnectionPhaseNameType ElectricalConnectionPhaseNameEnumType

// ElectricalConnectionPhaseNameEnumType type
type ElectricalConnectionPhaseNameEnumType string

// ElectricalConnectionPhaseNameEnumType constants
const (
	ElectricalConnectionPhaseNameEnumTypeA       ElectricalConnectionPhaseNameEnumType = "a"
	ElectricalConnectionPhaseNameEnumTypeB       ElectricalConnectionPhaseNameEnumType = "b"
	ElectricalConnectionPhaseNameEnumTypeC       ElectricalConnectionPhaseNameEnumType = "c"
	ElectricalConnectionPhaseNameEnumTypeAb      ElectricalConnectionPhaseNameEnumType = "ab"
	ElectricalConnectionPhaseNameEnumTypeBc      ElectricalConnectionPhaseNameEnumType = "bc"
	ElectricalConnectionPhaseNameEnumTypeAc      ElectricalConnectionPhaseNameEnumType = "ac"
	ElectricalConnectionPhaseNameEnumTypeAbc     ElectricalConnectionPhaseNameEnumType = "abc"
	ElectricalConnectionPhaseNameEnumTypeNeutral ElectricalConnectionPhaseNameEnumType = "neutral"
	ElectricalConnectionPhaseNameEnumTypeGround  ElectricalConnectionPhaseNameEnumType = "ground"
	ElectricalConnectionPhaseNameEnumTypeNone    ElectricalConnectionPhaseNameEnumType = "none"
)

// ElectricalConnectionConnectionPointType type
type ElectricalConnectionConnectionPointType string

// ElectricalConnectionConnectionPointType constants
const (
	ElectricalConnectionConnectionPointTypeGrid  ElectricalConnectionConnectionPointType = "grid"
	ElectricalConnectionConnectionPointTypeHome  ElectricalConnectionConnectionPointType = "home"
	ElectricalConnectionConnectionPointTypePv    ElectricalConnectionConnectionPointType = "pv"
	ElectricalConnectionConnectionPointTypeSd    ElectricalConnectionConnectionPointType = "sd"
	ElectricalConnectionConnectionPointTypeOther ElectricalConnectionConnectionPointType = "other"
)

// ElectricalConnectionParameterDescriptionDataType complex type
type ElectricalConnectionParameterDescriptionDataType struct {
	ElectricalConnectionId  *ElectricalConnectionIdType                `json:"electricalConnectionId,omitempty"`
	ParameterId             *ElectricalConnectionParameterIdType       `json:"parameterId,omitempty"`
	MeasurementId           *MeasurementIdType                         `json:"measurementId,omitempty"`
	VoltageType             *ElectricalConnectionVoltageTypeType       `json:"voltageType,omitempty"`
	AcMeasuredPhases        *ElectricalConnectionPhaseNameType         `json:"acMeasuredPhases,omitempty"`
	AcMeasuredInReferenceTo *ElectricalConnectionPhaseNameType         `json:"acMeasuredInReferenceTo,omitempty"`
	AcMeasurementType       *ElectricalConnectionAcMeasurementTypeType `json:"acMeasurementType,omitempty"`
	AcMeasurementVariant    *ElectricalConnectionMeasurandVariantType  `json:"acMeasurementVariant,omitempty"`
	AcMeasuredHarmonic      *uint8                                     `json:"acMeasuredHarmonic,omitempty"`
	ScopeType               *ScopeTypeType                             `json:"scopeType,omitempty"`
	Label                   *LabelType                                 `json:"label,omitempty"`
	Description             *DescriptionType                           `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionParameterDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionParameterDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionParameterDescriptionListDataType complex type
type ElectricalConnectionParameterDescriptionListDataType struct {
	ElectricalConnectionParameterDescriptionData []ElectricalConnectionParameterDescriptionDataType `json:"electricalConnectionParameterDescriptionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionParameterDescriptionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionParameterDescriptionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionParameterDescriptionListDataSelectorsType complex type
type ElectricalConnectionParameterDescriptionListDataSelectorsType struct {
	ElectricalConnectionId *ElectricalConnectionIdType          `json:"electricalConnectionId,omitempty"`
	ParameterId            *ElectricalConnectionParameterIdType `json:"parameterId,omitempty"`
	MeasurementId          *MeasurementIdType                   `json:"measurementId,omitempty"`
	ScopeType              *ScopeTypeType                       `json:"scopeType,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionParameterDescriptionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionParameterDescriptionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionPermittedValueSetDataType complex type
type ElectricalConnectionPermittedValueSetDataType struct {
	ElectricalConnectionId *ElectricalConnectionIdType          `json:"electricalConnectionId,omitempty"`
	ParameterId            *ElectricalConnectionParameterIdType `json:"parameterId,omitempty"`
	PermittedValueSet      []ScaledNumberSetType                `json:"permittedValueSet,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionPermittedValueSetDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionPermittedValueSetDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionPermittedValueSetListDataType complex type
type ElectricalConnectionPermittedValueSetListDataType struct {
	ElectricalConnectionPermittedValueSetData []ElectricalConnectionPermittedValueSetDataType `json:"electricalConnectionPermittedValueSetData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionPermittedValueSetListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionPermittedValueSetListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionPermittedValueSetListDataSelectorsType complex type
type ElectricalConnectionPermittedValueSetListDataSelectorsType struct {
	ElectricalConnectionId *ElectricalConnectionIdType          `json:"electricalConnectionId,omitempty"`
	ParameterId            *ElectricalConnectionParameterIdType `json:"parameterId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionPermittedValueSetListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionPermittedValueSetListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionStateDataType complex type
type ElectricalConnectionStateDataType struct {
	ElectricalConnectionId *ElectricalConnectionIdType `json:"electricalConnectionId,omitempty"`
	Timestamp              *AbsoluteOrRelativeTimeType `json:"timestamp,omitempty"`
	CurrentEnergyMode      *EnergyModeType             `json:"currentEnergyMode,omitempty"`
	ConsumptionTime        *string                     `json:"consumptionTime,omitempty"`
	ProductionTime         *string                     `json:"productionTime,omitempty"`
	TotalConsumptionTime   *string                     `json:"totalConsumptionTime,omitempty"`
	TotalProductionTime    *string                     `json:"totalProductionTime,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionStateDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionStateDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionStateListDataType complex type
type ElectricalConnectionStateListDataType struct {
	ElectricalConnectionStateData []ElectricalConnectionStateDataType `json:"electricalConnectionStateData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionStateListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionStateListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionStateListDataSelectorsType complex type
type ElectricalConnectionStateListDataSelectorsType struct {
	ElectricalConnectionId *ElectricalConnectionIdType `json:"electricalConnectionId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionStateListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionStateListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionDescriptionDataType complex type
type ElectricalConnectionDescriptionDataType struct {
	ElectricalConnectionId  *ElectricalConnectionIdType          `json:"electricalConnectionId,omitempty"`
	PowerSupplyType         *ElectricalConnectionVoltageTypeType `json:"powerSupplyType,omitempty"`
	AcConnectedPhases       *uint                                `json:"acConnectedPhases,omitempty"`
	AcRmsPeriodDuration     *string                              `json:"acRmsPeriodDuration,omitempty"`
	PositiveEnergyDirection *EnergyDirectionType                 `json:"positiveEnergyDirection,omitempty"`
	ScopeType               *ScopeTypeType                       `json:"scopeType,omitempty"`
	Label                   *LabelType                           `json:"label,omitempty"`
	Description             *DescriptionType                     `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionDescriptionListDataType complex type
type ElectricalConnectionDescriptionListDataType struct {
	ElectricalConnectionDescriptionData []ElectricalConnectionDescriptionDataType `json:"electricalConnectionDescriptionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionDescriptionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionDescriptionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// ElectricalConnectionDescriptionListDataSelectorsType complex type
type ElectricalConnectionDescriptionListDataSelectorsType struct {
	ElectricalConnectionId *ElectricalConnectionIdType `json:"electricalConnectionId,omitempty"`
	ScopeType              *ScopeTypeType              `json:"scopeType,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m ElectricalConnectionDescriptionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *ElectricalConnectionDescriptionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
