// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// IncentiveTableType complex type
type IncentiveTableType struct {
	Tariff        *TariffDataType                   `json:"tariff,omitempty"`
	IncentiveSlot []IncentiveTableIncentiveSlotType `json:"incentiveSlot,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableIncentiveSlotType complex type
type IncentiveTableIncentiveSlotType struct {
	TimeInterval *TimeTableDataType       `json:"timeInterval,omitempty"`
	Tier         []IncentiveTableTierType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableIncentiveSlotType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableIncentiveSlotType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableTierType complex type
type IncentiveTableTierType struct {
	Tier      *TierDataType          `json:"tier,omitempty"`
	Boundary  []TierBoundaryDataType `json:"boundary,omitempty"`
	Incentive []IncentiveDataType    `json:"incentive,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableTierType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableTierType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDataType complex type
type IncentiveTableDataType struct {
	IncentiveTable []IncentiveTableType `json:"incentiveTable,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDataSelectorsType complex type
type IncentiveTableDataSelectorsType struct {
	Tariff *TariffListDataSelectorsType `json:"tariff,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionType complex type
type IncentiveTableDescriptionType struct {
	TariffDescription *TariffDescriptionDataType          `json:"tariffDescription,omitempty"`
	Tier              []IncentiveTableDescriptionTierType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionTierType complex type
type IncentiveTableDescriptionTierType struct {
	TierDescription      *TierDescriptionDataType          `json:"tierDescription,omitempty"`
	BoundaryDescription  []TierBoundaryDescriptionDataType `json:"boundaryDescription,omitempty"`
	IncentiveDescription []IncentiveDescriptionDataType    `json:"incentiveDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionTierType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionTierType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionDataType complex type
type IncentiveTableDescriptionDataType struct {
	IncentiveTableDescription []IncentiveTableDescriptionType `json:"incentiveTableDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionDataSelectorsType complex type
type IncentiveTableDescriptionDataSelectorsType struct {
	TariffDescription *TariffDescriptionListDataSelectorsType `json:"tariffDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsType complex type
type IncentiveTableConstraintsType struct {
	Tariff                   *TariffDataType                   `json:"tariff,omitempty"`
	TariffConstraints        *TariffOverallConstraintsDataType `json:"tariffConstraints,omitempty"`
	IncentiveSlotConstraints *TimeTableConstraintsDataType     `json:"incentiveSlotConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsDataType complex type
type IncentiveTableConstraintsDataType struct {
	IncentiveTableConstraints []IncentiveTableConstraintsType `json:"incentiveTableConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsDataSelectorsType complex type
type IncentiveTableConstraintsDataSelectorsType struct {
	Tariff *TariffListDataSelectorsType `json:"tariff,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
