// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// IncentiveTableType complex type
type IncentiveTableType struct {
	Tariff        *TariffDataType                   `json:"tariff,omitempty"`
	IncentiveSlot []IncentiveTableIncentiveSlotType `json:"incentiveSlot,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableIncentiveSlotType complex type
type IncentiveTableIncentiveSlotType struct {
	TimeInterval *TimeTableDataType       `json:"timeInterval,omitempty"`
	Tier         []IncentiveTableTierType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableIncentiveSlotType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableIncentiveSlotType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableTierType complex type
type IncentiveTableTierType struct {
	Tier      *TierDataType          `json:"tier,omitempty"`
	Boundary  []TierBoundaryDataType `json:"boundary,omitempty"`
	Incentive []IncentiveDataType    `json:"incentive,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableTierType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableTierType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDataType complex type
type IncentiveTableDataType struct {
	IncentiveTable []IncentiveTableType `json:"incentiveTable,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableElementsType complex type
type IncentiveTableElementsType struct {
	Tariff        *TariffDataElementsType                  `json:"tariff,omitempty"`
	IncentiveSlot *IncentiveTableIncentiveSlotElementsType `json:"incentiveSlot,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableIncentiveSlotElementsType complex type
type IncentiveTableIncentiveSlotElementsType struct {
	TimeInterval *TimeTableDataElementsType      `json:"timeInterval,omitempty"`
	Tier         *IncentiveTableTierElementsType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableIncentiveSlotElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableIncentiveSlotElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableTierElementsType complex type
type IncentiveTableTierElementsType struct {
	Tier      *TierDataElementsType         `json:"tier,omitempty"`
	Boundary  *TierBoundaryDataElementsType `json:"boundary,omitempty"`
	Incentive *IncentiveDataElementsType    `json:"incentive,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableTierElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableTierElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDataElementsType complex type
type IncentiveTableDataElementsType struct {
	IncentiveTable *IncentiveTableElementsType `json:"incentiveTable,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDataSelectorsType complex type
type IncentiveTableDataSelectorsType struct {
	Tariff *TariffListDataSelectorsType `json:"tariff,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionType complex type
type IncentiveTableDescriptionType struct {
	TariffDescription *TariffDescriptionDataType          `json:"tariffDescription,omitempty"`
	Tier              []IncentiveTableDescriptionTierType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionTierType complex type
type IncentiveTableDescriptionTierType struct {
	TierDescription      *TierDescriptionDataType          `json:"tierDescription,omitempty"`
	BoundaryDescription  []TierBoundaryDescriptionDataType `json:"boundaryDescription,omitempty"`
	IncentiveDescription []IncentiveDescriptionDataType    `json:"incentiveDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionTierType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionTierType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionDataType complex type
type IncentiveTableDescriptionDataType struct {
	IncentiveTableDescription []IncentiveTableDescriptionType `json:"incentiveTableDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionElementsType complex type
type IncentiveTableDescriptionElementsType struct {
	TariffDescription *TariffDescriptionDataElementsType         `json:"tariffDescription,omitempty"`
	Tier              *IncentiveTableDescriptionTierElementsType `json:"tier,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionTierElementsType complex type
type IncentiveTableDescriptionTierElementsType struct {
	TierDescription      *TierDescriptionDataElementsType         `json:"tierDescription,omitempty"`
	BoundaryDescription  *TierBoundaryDescriptionDataElementsType `json:"boundaryDescription,omitempty"`
	IncentiveDescription *IncentiveDescriptionDataElementsType    `json:"incentiveDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionTierElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionTierElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionDataElementsType complex type
type IncentiveTableDescriptionDataElementsType struct {
	IncentiveTableDescription *IncentiveTableDescriptionElementsType `json:"incentiveTableDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableDescriptionDataSelectorsType complex type
type IncentiveTableDescriptionDataSelectorsType struct {
	TariffDescription *TariffDescriptionListDataSelectorsType `json:"tariffDescription,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableDescriptionDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableDescriptionDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsType complex type
type IncentiveTableConstraintsType struct {
	Tariff                   *TariffDataType                   `json:"tariff,omitempty"`
	TariffConstraints        *TariffOverallConstraintsDataType `json:"tariffConstraints,omitempty"`
	IncentiveSlotConstraints *TimeTableConstraintsDataType     `json:"incentiveSlotConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsDataType complex type
type IncentiveTableConstraintsDataType struct {
	IncentiveTableConstraints []IncentiveTableConstraintsType `json:"incentiveTableConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsElementsType complex type
type IncentiveTableConstraintsElementsType struct {
	Tariff                   *TariffDataElementsType                   `json:"tariff,omitempty"`
	TariffConstraints        *TariffOverallConstraintsDataElementsType `json:"tariffConstraints,omitempty"`
	IncentiveSlotConstraints *TimeTableConstraintsDataElementsType     `json:"incentiveSlotConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsDataElementsType complex type
type IncentiveTableConstraintsDataElementsType struct {
	IncentiveTableConstraints *IncentiveTableConstraintsElementsType `json:"incentiveTableConstraints,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// IncentiveTableConstraintsDataSelectorsType complex type
type IncentiveTableConstraintsDataSelectorsType struct {
	Tariff *TariffListDataSelectorsType `json:"tariff,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m IncentiveTableConstraintsDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *IncentiveTableConstraintsDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
