// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// MeasurementIdType type
type MeasurementIdType uint

// MeasurementTypeType type
type MeasurementTypeType MeasurementTypeEnumType

// MeasurementTypeEnumType type
type MeasurementTypeEnumType string

// MeasurementTypeEnumType constants
const (
	MeasurementTypeEnumTypeAcceleration        MeasurementTypeEnumType = "acceleration"
	MeasurementTypeEnumTypeAngle               MeasurementTypeEnumType = "angle"
	MeasurementTypeEnumTypeAngularVelocity     MeasurementTypeEnumType = "angularVelocity"
	MeasurementTypeEnumTypeArea                MeasurementTypeEnumType = "area"
	MeasurementTypeEnumTypeAtmosphericPressure MeasurementTypeEnumType = "atmosphericPressure"
	MeasurementTypeEnumTypeCapacity            MeasurementTypeEnumType = "capacity"
	MeasurementTypeEnumTypeConcentration       MeasurementTypeEnumType = "concentration"
	MeasurementTypeEnumTypeCount               MeasurementTypeEnumType = "count"
	MeasurementTypeEnumTypeCurrent             MeasurementTypeEnumType = "current"
	MeasurementTypeEnumTypeDensity             MeasurementTypeEnumType = "density"
	MeasurementTypeEnumTypeDistance            MeasurementTypeEnumType = "distance"
	MeasurementTypeEnumTypeElectricField       MeasurementTypeEnumType = "electricField"
	MeasurementTypeEnumTypeEnergy              MeasurementTypeEnumType = "energy"
	MeasurementTypeEnumTypeForce               MeasurementTypeEnumType = "force"
	MeasurementTypeEnumTypeFrequency           MeasurementTypeEnumType = "frequency"
	MeasurementTypeEnumTypeHarmonicDistortion  MeasurementTypeEnumType = "harmonicDistortion"
	MeasurementTypeEnumTypeHeat                MeasurementTypeEnumType = "heat"
	MeasurementTypeEnumTypeHeatFlux            MeasurementTypeEnumType = "heatFlux"
	MeasurementTypeEnumTypeIlluminance         MeasurementTypeEnumType = "illuminance"
	MeasurementTypeEnumTypeImpulse             MeasurementTypeEnumType = "impulse"
	MeasurementTypeEnumTypeLevel               MeasurementTypeEnumType = "level"
	MeasurementTypeEnumTypeMagneticField       MeasurementTypeEnumType = "magneticField"
	MeasurementTypeEnumTypeMass                MeasurementTypeEnumType = "mass"
	MeasurementTypeEnumTypeMassFlow            MeasurementTypeEnumType = "massFlow"
	MeasurementTypeEnumTypeParticles           MeasurementTypeEnumType = "particles"
	MeasurementTypeEnumTypePercentage          MeasurementTypeEnumType = "percentage"
	MeasurementTypeEnumTypePower               MeasurementTypeEnumType = "power"
	MeasurementTypeEnumTypePowerFactor         MeasurementTypeEnumType = "powerFactor"
	MeasurementTypeEnumTypePressure            MeasurementTypeEnumType = "pressure"
	MeasurementTypeEnumTypeRadonActivity       MeasurementTypeEnumType = "radonActivity"
	MeasurementTypeEnumTypeRelativeHumidity    MeasurementTypeEnumType = "relativeHumidity"
	MeasurementTypeEnumTypeResistance          MeasurementTypeEnumType = "resistance"
	MeasurementTypeEnumTypeSolarRadiation      MeasurementTypeEnumType = "solarRadiation"
	MeasurementTypeEnumTypeSpeed               MeasurementTypeEnumType = "speed"
	MeasurementTypeEnumTypeTemperature         MeasurementTypeEnumType = "temperature"
	MeasurementTypeEnumTypeTime                MeasurementTypeEnumType = "time"
	MeasurementTypeEnumTypeTorque              MeasurementTypeEnumType = "torque"
	MeasurementTypeEnumTypeUnknown             MeasurementTypeEnumType = "unknown"
	MeasurementTypeEnumTypeVelocity            MeasurementTypeEnumType = "velocity"
	MeasurementTypeEnumTypeVoltage             MeasurementTypeEnumType = "voltage"
	MeasurementTypeEnumTypeVolume              MeasurementTypeEnumType = "volume"
	MeasurementTypeEnumTypeVolumetricFlow      MeasurementTypeEnumType = "volumetricFlow"
)

// MeasurementValueTypeType type
type MeasurementValueTypeType MeasurementValueTypeEnumType

// MeasurementValueTypeEnumType type
type MeasurementValueTypeEnumType string

// MeasurementValueTypeEnumType constants
const (
	MeasurementValueTypeEnumTypeValue             MeasurementValueTypeEnumType = "value"
	MeasurementValueTypeEnumTypeAverageValue      MeasurementValueTypeEnumType = "averageValue"
	MeasurementValueTypeEnumTypeMinvValue         MeasurementValueTypeEnumType = "minValue"
	MeasurementValueTypeEnumTypeMaxvVlue          MeasurementValueTypeEnumType = "maxValue"
	MeasurementValueTypeEnumTypeStandardDeviation MeasurementValueTypeEnumType = "standardDeviation"
)

// MeasurementValueSourceType type
type MeasurementValueSourceType MeasurementValueSourceEnumType

// MeasurementValueSourceEnumType type
type MeasurementValueSourceEnumType string

// MeasurementValueSourceEnumType constants
const (
	MeasurementValueSourceEnumTypeMeasuredValue   MeasurementValueSourceEnumType = "measuredValue"
	MeasurementValueSourceEnumTypeCalculatedValue MeasurementValueSourceEnumType = "calculatedValue"
	MeasurementValueSourceEnumTypeEmpiricalValue  MeasurementValueSourceEnumType = "empiricalValue"
)

// MeasurementValueTendencyType type
type MeasurementValueTendencyType MeasurementValueTendencyEnumType

// MeasurementValueTendencyEnumType type
type MeasurementValueTendencyEnumType string

// MeasurementValueTendencyEnumType constants
const (
	MeasurementValueTendencyEnumTypeRising  MeasurementValueTendencyEnumType = "rising"
	MeasurementValueTendencyEnumTypeStable  MeasurementValueTendencyEnumType = "stable"
	MeasurementValueTendencyEnumTypeFalling MeasurementValueTendencyEnumType = "falling"
)

// MeasurementValueStateType type
type MeasurementValueStateType MeasurementValueStateEnumType

// MeasurementValueStateEnumType type
type MeasurementValueStateEnumType string

// MeasurementValueStateEnumType constants
const (
	MeasurementValueStateEnumTypeNormal     MeasurementValueStateEnumType = "normal"
	MeasurementValueStateEnumTypeOutofrange MeasurementValueStateEnumType = "outOfRange"
	MeasurementValueStateEnumTypeError      MeasurementValueStateEnumType = "error"
)

// MeasurementDataType complex type
type MeasurementDataType struct {
	MeasurementId    *MeasurementIdType            `json:"measurementId,omitempty"`
	ValueType        *MeasurementValueTypeType     `json:"valueType,omitempty"`
	Timestamp        *string                       `json:"timestamp,omitempty"`
	Value            *ScaledNumberType             `json:"value,omitempty"`
	EvaluationPeriod *TimePeriodType               `json:"evaluationPeriod,omitempty"`
	ValueSource      *MeasurementValueSourceType   `json:"valueSource,omitempty"`
	ValueTendency    *MeasurementValueTendencyType `json:"valueTendency,omitempty"`
	ValueState       *MeasurementValueStateType    `json:"valueState,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementListDataType complex type
type MeasurementListDataType struct {
	MeasurementData []MeasurementDataType `json:"measurementData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementListDataSelectorsType complex type
type MeasurementListDataSelectorsType struct {
	MeasurementId     *MeasurementIdType        `json:"measurementId,omitempty"`
	ValueType         *MeasurementValueTypeType `json:"valueType,omitempty"`
	TimestampInterval *TimestampIntervalType    `json:"timestampInterval,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementConstraintsDataType complex type
type MeasurementConstraintsDataType struct {
	MeasurementId *MeasurementIdType `json:"measurementId,omitempty"`
	ValueRangeMin *ScaledNumberType  `json:"valueRangeMin,omitempty"`
	ValueRangeMax *ScaledNumberType  `json:"valueRangeMax,omitempty"`
	ValueStepSize *ScaledNumberType  `json:"valueStepSize,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementConstraintsDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementConstraintsDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementConstraintsListDataType complex type
type MeasurementConstraintsListDataType struct {
	MeasurementConstraintsData []MeasurementConstraintsDataType `json:"measurementConstraintsData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementConstraintsListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementConstraintsListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementConstraintsListDataSelectorsType complex type
type MeasurementConstraintsListDataSelectorsType struct {
	MeasurementId *MeasurementIdType `json:"measurementId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementConstraintsListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementConstraintsListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementDescriptionDataType complex type
type MeasurementDescriptionDataType struct {
	MeasurementId    *MeasurementIdType     `json:"measurementId,omitempty"`
	MeasurementType  *MeasurementTypeType   `json:"measurementType,omitempty"`
	CommodityType    *CommodityTypeType     `json:"commodityType,omitempty"`
	Unit             *UnitOfMeasurementType `json:"unit,omitempty"`
	CalibrationValue *ScaledNumberType      `json:"calibrationValue,omitempty"`
	ScopeType        *ScopeTypeType         `json:"scopeType,omitempty"`
	Label            *LabelType             `json:"label,omitempty"`
	Description      *DescriptionType       `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementDescriptionListDataType complex type
type MeasurementDescriptionListDataType struct {
	MeasurementDescriptionData []MeasurementDescriptionDataType `json:"measurementDescriptionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementDescriptionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementDescriptionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementDescriptionListDataSelectorsType complex type
type MeasurementDescriptionListDataSelectorsType struct {
	MeasurementId   *MeasurementIdType   `json:"measurementId,omitempty"`
	MeasurementType *MeasurementTypeType `json:"measurementType,omitempty"`
	CommodityType   *CommodityTypeType   `json:"commodityType,omitempty"`
	ScopeType       *ScopeTypeType       `json:"scopeType,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementDescriptionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementDescriptionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementThresholdRelationDataType complex type
type MeasurementThresholdRelationDataType struct {
	MeasurementId *MeasurementIdType `json:"measurementId,omitempty"`
	ThresholdId   []ThresholdIdType  `json:"thresholdId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementThresholdRelationDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementThresholdRelationDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementThresholdRelationListDataType complex type
type MeasurementThresholdRelationListDataType struct {
	MeasurementThresholdRelationData []MeasurementThresholdRelationDataType `json:"measurementThresholdRelationData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementThresholdRelationListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementThresholdRelationListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// MeasurementThresholdRelationListDataSelectorsType complex type
type MeasurementThresholdRelationListDataSelectorsType struct {
	MeasurementId *MeasurementIdType `json:"measurementId,omitempty"`
	ThresholdId   *ThresholdIdType   `json:"thresholdId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m MeasurementThresholdRelationListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *MeasurementThresholdRelationListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
