// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// TimeTableIdType type
type TimeTableIdType uint

// TimeSlotIdType type
type TimeSlotIdType uint

// TimeSlotCountType type
type TimeSlotCountType TimeSlotIdType

// TimeSlotTimeModeType type
type TimeSlotTimeModeType TimeSlotTimeModeEnumType

// TimeSlotTimeModeEnumType type
type TimeSlotTimeModeEnumType string

// TimeSlotTimeModeEnumType constants
const (
	TimeSlotTimeModeEnumTypeAbsolute  TimeSlotTimeModeEnumType = "absolute"
	TimeSlotTimeModeEnumTypeRecurring TimeSlotTimeModeEnumType = "recurring"
	TimeSlotTimeModeEnumTypeBoth      TimeSlotTimeModeEnumType = "both"
)

// TimeTableDataType complex type
type TimeTableDataType struct {
	TimeTableId           *TimeTableIdType             `json:"timeTableId,omitempty"`
	TimeSlotId            *TimeSlotIdType              `json:"timeSlotId,omitempty"`
	RecurrenceInformation *RecurrenceInformationType   `json:"recurrenceInformation,omitempty"`
	StartTime             *AbsoluteOrRecurringTimeType `json:"startTime,omitempty"`
	EndTime               *AbsoluteOrRecurringTimeType `json:"endTime,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableListDataType complex type
type TimeTableListDataType struct {
	TimeTableData []TimeTableDataType `json:"timeTableData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableListDataSelectorsType complex type
type TimeTableListDataSelectorsType struct {
	TimeTableId *TimeTableIdType `json:"timeTableId,omitempty"`
	TimeSlotId  *TimeSlotIdType  `json:"timeSlotId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableConstraintsDataType complex type
type TimeTableConstraintsDataType struct {
	TimeTableId          *uint              `json:"timeTableId,omitempty"`
	SlotCountMin         *TimeSlotCountType `json:"slotCountMin,omitempty"`
	SlotCountMax         *TimeSlotCountType `json:"slotCountMax,omitempty"`
	SlotDurationMin      *string            `json:"slotDurationMin,omitempty"`
	SlotDurationMax      *string            `json:"slotDurationMax,omitempty"`
	SlotDurationStepSize *string            `json:"slotDurationStepSize,omitempty"`
	SlotShiftStepSize    *string            `json:"slotShiftStepSize,omitempty"`
	FirstSlotBeginsAt    *string            `json:"firstSlotBeginsAt,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableConstraintsDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableConstraintsDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableConstraintsListDataType complex type
type TimeTableConstraintsListDataType struct {
	TimeTableConstraintsData []TimeTableConstraintsDataType `json:"timeTableConstraintsData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableConstraintsListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableConstraintsListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableConstraintsListDataSelectorsType complex type
type TimeTableConstraintsListDataSelectorsType struct {
	TimeTableId *TimeTableIdType `json:"timeTableId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableConstraintsListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableConstraintsListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableDescriptionDataType complex type
type TimeTableDescriptionDataType struct {
	TimeTableId             *uint                 `json:"timeTableId,omitempty"`
	TimeSlotCountChangeable *bool                 `json:"timeSlotCountChangeable,omitempty"`
	TimeSlotTimesChangeable *bool                 `json:"timeSlotTimesChangeable,omitempty"`
	TimeSlotTimeMode        *TimeSlotTimeModeType `json:"timeSlotTimeMode,omitempty"`
	Label                   *LabelType            `json:"label,omitempty"`
	Description             *DescriptionType      `json:"description,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableDescriptionDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableDescriptionDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableDescriptionListDataType complex type
type TimeTableDescriptionListDataType struct {
	TimeTableDescriptionData []TimeTableDescriptionDataType `json:"timeTableDescriptionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableDescriptionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableDescriptionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// TimeTableDescriptionListDataSelectorsType complex type
type TimeTableDescriptionListDataSelectorsType struct {
	TimeTableId *TimeTableIdType `json:"timeTableId,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m TimeTableDescriptionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *TimeTableDescriptionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
