// Package ns_p contains models for http://docs.eebus.org/spine/xsd/v1
package model

// Code generated by github.com/andig/xsd2go. DO NOT EDIT.

import "github.com/evcc-io/eebus/util"

// SpecificationVersionDataType complex type
type SpecificationVersionDataType SpecificationVersionType

// SpecificationVersionDataElementsType complex type
type SpecificationVersionDataElementsType struct {
}

// MarshalJSON is the SHIP serialization marshaller
func (m SpecificationVersionDataElementsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *SpecificationVersionDataElementsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// SpecificationVersionListDataType complex type
type SpecificationVersionListDataType struct {
	SpecificationVersionData []SpecificationVersionDataType `json:"specificationVersionData,omitempty"`
}

// MarshalJSON is the SHIP serialization marshaller
func (m SpecificationVersionListDataType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *SpecificationVersionListDataType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}

// SpecificationVersionListDataSelectorsType complex type
type SpecificationVersionListDataSelectorsType struct {
}

// MarshalJSON is the SHIP serialization marshaller
func (m SpecificationVersionListDataSelectorsType) MarshalJSON() ([]byte, error) {
	return util.Marshal(m)
}

// UnmarshalJSON is the SHIP serialization unmarshaller
func (m *SpecificationVersionListDataSelectorsType) UnmarshalJSON(data []byte) error {
	return util.Unmarshal(data, &m)
}
